[package]
name = "task-efr32mg24-task-viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
userlib = { path = "../../sys/userlib", features = ["panic-messages"] }
hubris-num-tasks = { path = "../../sys/num-tasks" }
efr32mg24-gfx = { path = "../../lib/efr32mg24-gfx" }
embedded-graphics = "0.8"

[[bin]]
name = "task-efr32mg24-task-viewer"
test = false
bench = false

[lints]
workspace = true
